// Mock data for development - replace with actual API calls

import type { Cliente, Incapacidad, DocumentoAnalizado, ResumenAnalisis } from "./types";

export const mockClientes: Cliente[] = [
  {
    id: "1",
    nombre: "Carlos Andres Martinez",
    documento: "1023456789",
    empresa: "Tech Solutions SAS",
    cargo: "Desarrollador Senior",
    email: "carlos.martinez@techsolutions.com",
    telefono: "3001234567",
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    nombre: "Maria Fernanda Lopez",
    documento: "1098765432",
    empresa: "Tech Solutions SAS",
    cargo: "Analista de Datos",
    email: "maria.lopez@techsolutions.com",
    telefono: "3009876543",
    createdAt: "2024-02-20",
  },
  {
    id: "3",
    nombre: "Juan Pablo Rodriguez",
    documento: "1012345678",
    empresa: "Innovar Colombia",
    cargo: "Gerente de Proyectos",
    email: "juan.rodriguez@innovar.co",
    telefono: "3005551234",
    createdAt: "2024-03-10",
  },
];

export const mockIncapacidades: Incapacidad[] = [
  {
    id: "inc-001",
    clienteId: "1",
    clienteNombre: "Carlos Andres Martinez",
    numeroRadicado: "RAD-2024-001234",
    fechaInicio: "2024-05-01",
    fechaFin: "2024-05-05",
    diasIncapacidad: 5,
    diagnostico: "Infeccion respiratoria aguda",
    codigoCie10: "J06.9",
    eps: "Sanitas",
    medicoTratante: "Dr. Roberto Gomez",
    estado: "correcto",
    createdAt: "2024-05-01",
  },
  {
    id: "inc-002",
    clienteId: "2",
    clienteNombre: "Maria Fernanda Lopez",
    numeroRadicado: "RAD-2024-001235",
    fechaInicio: "2024-05-10",
    fechaFin: "2024-05-15",
    diasIncapacidad: 6,
    diagnostico: "Lumbalgia",
    codigoCie10: "M54.5",
    eps: "Nueva EPS",
    medicoTratante: "Dra. Patricia Vargas",
    estado: "inconsistente",
    observaciones: "Fechas no coinciden con diagnostico",
    createdAt: "2024-05-10",
  },
  {
    id: "inc-003",
    clienteId: "3",
    clienteNombre: "Juan Pablo Rodriguez",
    numeroRadicado: "RAD-2024-001236",
    fechaInicio: "2024-05-20",
    fechaFin: "2024-05-22",
    diasIncapacidad: 3,
    diagnostico: "Gastroenteritis aguda",
    codigoCie10: "A09",
    eps: "Sura",
    estado: "ilegible",
    observaciones: "Documento borroso, no se puede leer completamente",
    createdAt: "2024-05-20",
  },
];

export const mockDocumentosAnalizados: DocumentoAnalizado[] = [
  {
    id: "doc-001",
    nombreArchivo: "incapacidad_martinez_mayo2024.pdf",
    estado: "correcto",
    confianza: 98.5,
    datosExtraidos: {
      nombrePaciente: "Carlos Andres Martinez",
      documentoPaciente: "1023456789",
      fechaInicio: "2024-05-01",
      fechaFin: "2024-05-05",
      diasIncapacidad: 5,
      diagnostico: "Infeccion respiratoria aguda",
      codigoCie10: "J06.9",
      eps: "Sanitas",
      numeroRadicado: "RAD-2024-001234",
    },
    archivoUrl: "/documents/doc-001.pdf",
    createdAt: "2024-05-01",
  },
  {
    id: "doc-002",
    nombreArchivo: "incapacidad_lopez_mayo2024.pdf",
    estado: "inconsistente",
    confianza: 72.3,
    inconsistencias: [
      {
        campo: "fechaFin",
        valorDetectado: "2024-05-18",
        valorEsperado: "2024-05-15",
        tipo: "valor_sospechoso",
        posicion: { pagina: 1, x: 250, y: 320, width: 100, height: 20 },
      },
      {
        campo: "diasIncapacidad",
        valorDetectado: "9",
        valorEsperado: "6",
        tipo: "valor_sospechoso",
        posicion: { pagina: 1, x: 400, y: 320, width: 30, height: 20 },
      },
    ],
    datosExtraidos: {
      nombrePaciente: "Maria Fernanda Lopez",
      documentoPaciente: "1098765432",
      fechaInicio: "2024-05-10",
      fechaFin: "2024-05-18",
      diasIncapacidad: 9,
      diagnostico: "Lumbalgia",
      codigoCie10: "M54.5",
      eps: "Nueva EPS",
      numeroRadicado: "RAD-2024-001235",
    },
    archivoUrl: "/documents/doc-002.pdf",
    createdAt: "2024-05-10",
  },
  {
    id: "doc-003",
    nombreArchivo: "incapacidad_rodriguez_mayo2024.pdf",
    estado: "ilegible",
    confianza: 35.2,
    inconsistencias: [
      {
        campo: "nombrePaciente",
        valorDetectado: "???",
        tipo: "ilegible",
        posicion: { pagina: 1, x: 150, y: 100, width: 200, height: 25 },
      },
      {
        campo: "diagnostico",
        valorDetectado: "Gastro...",
        tipo: "ilegible",
        posicion: { pagina: 1, x: 150, y: 250, width: 250, height: 25 },
      },
    ],
    datosExtraidos: {
      documentoPaciente: "1012345678",
      fechaInicio: "2024-05-20",
      eps: "Sura",
    },
    archivoUrl: "/documents/doc-003.pdf",
    createdAt: "2024-05-20",
  },
  {
    id: "doc-004",
    nombreArchivo: "incapacidad_garcia_abril2024.pdf",
    estado: "correcto",
    confianza: 95.8,
    datosExtraidos: {
      nombrePaciente: "Ana Maria Garcia",
      documentoPaciente: "1056789012",
      fechaInicio: "2024-04-15",
      fechaFin: "2024-04-17",
      diasIncapacidad: 3,
      diagnostico: "Migrania severa",
      codigoCie10: "G43.9",
      eps: "Compensar",
      numeroRadicado: "RAD-2024-001200",
    },
    archivoUrl: "/documents/doc-004.pdf",
    createdAt: "2024-04-15",
  },
  {
    id: "doc-005",
    nombreArchivo: "incapacidad_sanchez_abril2024.pdf",
    estado: "inconsistente",
    confianza: 68.4,
    inconsistencias: [
      {
        campo: "codigoCie10",
        valorDetectado: "XYZ123",
        tipo: "formato",
        posicion: { pagina: 1, x: 300, y: 280, width: 80, height: 20 },
      },
    ],
    datosExtraidos: {
      nombrePaciente: "Pedro Sanchez",
      documentoPaciente: "1087654321",
      fechaInicio: "2024-04-20",
      fechaFin: "2024-04-25",
      diasIncapacidad: 6,
      diagnostico: "Fractura de muneca",
      codigoCie10: "XYZ123",
      eps: "Famisanar",
      numeroRadicado: "RAD-2024-001210",
    },
    archivoUrl: "/documents/doc-005.pdf",
    createdAt: "2024-04-20",
  },
];

export const mockResumen: ResumenAnalisis = {
  totalDocumentos: 5,
  correctos: 2,
  inconsistentes: 2,
  ilegibles: 1,
  porcentajeCorrectos: 40,
  porcentajeInconsistentes: 40,
  porcentajeIlegibles: 20,
};

// Loading messages for AI analysis
export const loadingMessages = [
  "Iniciando analisis...",
  "Preparando documentos...",
  "Leyendo archivos PDF...",
  "Extrayendo texto con OCR...",
  "Analizando estructura del documento...",
  "Identificando campos clave...",
  "Validando codigos CIE-10...",
  "Verificando fechas y periodos...",
  "Detectando inconsistencias...",
  "Calculando confianza...",
  "Generando resumen...",
  "Ya casi esta listo...",
  "Finalizando analisis...",
];
